// Code generated by MockGen. DO NOT EDIT.
// Source: ./timeline_repository.go

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	entity "gosocialgraph/pkg/entity"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockTimelineReader is a mock of TimelineReader interface.
type MockTimelineReader struct {
	ctrl     *gomock.Controller
	recorder *MockTimelineReaderMockRecorder
}

// MockTimelineReaderMockRecorder is the mock recorder for MockTimelineReader.
type MockTimelineReaderMockRecorder struct {
	mock *MockTimelineReader
}

// NewMockTimelineReader creates a new mock instance.
func NewMockTimelineReader(ctrl *gomock.Controller) *MockTimelineReader {
	mock := &MockTimelineReader{ctrl: ctrl}
	mock.recorder = &MockTimelineReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTimelineReader) EXPECT() *MockTimelineReaderMockRecorder {
	return m.recorder
}

// All mocks base method.
func (m *MockTimelineReader) All(ctx context.Context) ([]entity.UserPost, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "All", ctx)
	ret0, _ := ret[0].([]entity.UserPost)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// All indicates an expected call of All.
func (mr *MockTimelineReaderMockRecorder) All(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "All", reflect.TypeOf((*MockTimelineReader)(nil).All), ctx)
}

// TimelineFor mocks base method.
func (m *MockTimelineReader) TimelineFor(ctx context.Context, userID uuid.UUID) ([]entity.UserPost, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TimelineFor", ctx, userID)
	ret0, _ := ret[0].([]entity.UserPost)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TimelineFor indicates an expected call of TimelineFor.
func (mr *MockTimelineReaderMockRecorder) TimelineFor(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TimelineFor", reflect.TypeOf((*MockTimelineReader)(nil).TimelineFor), ctx, userID)
}

// UserPosts mocks base method.
func (m *MockTimelineReader) UserPosts(ctx context.Context, userID uuid.UUID) ([]entity.UserPost, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserPosts", ctx, userID)
	ret0, _ := ret[0].([]entity.UserPost)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UserPosts indicates an expected call of UserPosts.
func (mr *MockTimelineReaderMockRecorder) UserPosts(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserPosts", reflect.TypeOf((*MockTimelineReader)(nil).UserPosts), ctx, userID)
}
