openapi: 3.0.0
servers:
  - description: Social Graph Development
    url: http://localhost:3010/

info:
  version: "1.0.0"
  title: Go Social Graph API
  description: >-
    This is an example of using OAuth2 Access Code Flow in a specification to
    describe security to your API.

paths:
  /api/user:
    post:
      summary: Create a new user
      operationId: createUser
      tags:
      - user
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                username:
                  type: string
              
      responses:
        201:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateUserResponse'

components:
  schemas:
    CreateUserIntent:
      properties:
        username:
          type: string
    
    CreateUserResponse:
      properties:
        id:
          type: string
          format: uuid
        username:
          type: string
        created_at:
          type: string
          format: date-time
      required:
        - id
        - username
        - created_at