// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.2 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8RUX0/jOBD/KtbcPQaSwlveOE7HoV0JxO4+rSo0JJPGKLGNPSlUVb77apyUNlDKCgnt",
	"U1N7bP/m92fWUNjWWUOGA+RrCEVNLcbPc0/IdG0D39BDR4Fl0XnryLOmWFJYw2TiRotPX8ksuIZ8liXA",
	"K0eQQ2CvzQL6BLpA/laXUlpZ3yJDDl2nS3hV2yfg6aHTnkrIfz4fTJ5fm/fJBFxw1gQ6iO4VnI8geQPE",
	"j0D+AIhYU94iTx4skemIdUuQfBDcQKnBlvY0uA/5c3myC2reS7E2lZVrSgqF1461NZDD91oHpYNCo+gJ",
	"W9eQspXqgjYLdXXWcX2izoqCQlDntiT1X2MflTYKVXBU6EoXKBcptmq4945UoKLzmleyuLKdV2fXl8fS",
	"nOZGGriw6pstNDbqwqOrZRsSWJIPA6TZcXacSfPWkUGnIYfTuJSAQ64j5Sk6nTo7Gnb8FU0inMsSchDj",
	"/I+mbMjDQBUF/seWqxe+QeeasY30PgiCTUTk629PFeTwV7rNUDoGKH2dnkj0lODHWhe1EmEUmlJtHt4V",
	"j31HUc3BYLHBkyz7FJyjh/cAvfoSPRW6tkW/gny0vkJl6FEJx6qy0kRsRvTERRDnRfrncnZQxdtKN5Su",
	"x1T3Am9B+xQaKrciOfTYEpOXe9egBZZIDgkMIdiZFFP6kh0q3kv8/NOpnoyL36H6hthrWtLgk5FBJYmV",
	"VuTQlu7I/pbu+PfNEGzxHMxA2zWsHXpO5cWjEhmnPU8H3uGpNK7Yu3sqxki85/XZnxZg4vUX/t4QLgfI",
	"LzfunN44mWj/0pIa69oh6J1vIIea2eVp2tgCm9oGzk+zWZZCP+9/BQAA//8JEx7moAcAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
