// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.2 DO NOT EDIT.
package openapi

import (
	"time"

	openapi_types "github.com/deepmap/oapi-codegen/pkg/types"
)

// CreatePostRequest defines model for CreatePostRequest.
type CreatePostRequest struct {
	Content string             `json:"content"`
	UserId  openapi_types.UUID `json:"user_id"`
}

// CreatePostResponse defines model for CreatePostResponse.
type CreatePostResponse struct {
	Content string             `json:"content"`
	Id      openapi_types.UUID `json:"id"`
}

// CreateUserResponse defines model for CreateUserResponse.
type CreateUserResponse struct {
	CreatedAt time.Time          `json:"created_at"`
	Id        openapi_types.UUID `json:"id"`
	Username  string             `json:"username"`
}

// CreateUserMultipartBody defines parameters for CreateUser.
type CreateUserMultipartBody struct {
	Username *string `json:"username,omitempty"`
}

// FollowHandlerJSONBody defines parameters for FollowHandler.
type FollowHandlerJSONBody struct {
	From *openapi_types.UUID `json:"from,omitempty"`
}

// UnfollowHandlerJSONBody defines parameters for UnfollowHandler.
type UnfollowHandlerJSONBody struct {
	From *openapi_types.UUID `json:"from,omitempty"`
}

// PostHandlerJSONRequestBody defines body for PostHandler for application/json ContentType.
type PostHandlerJSONRequestBody = CreatePostRequest

// CreateUserMultipartRequestBody defines body for CreateUser for multipart/form-data ContentType.
type CreateUserMultipartRequestBody CreateUserMultipartBody

// FollowHandlerJSONRequestBody defines body for FollowHandler for application/json ContentType.
type FollowHandlerJSONRequestBody FollowHandlerJSONBody

// UnfollowHandlerJSONRequestBody defines body for UnfollowHandler for application/json ContentType.
type UnfollowHandlerJSONRequestBody UnfollowHandlerJSONBody
