// Code generated by MockGen. DO NOT EDIT.
// Source: ./unfollow_service.go

// Package mock_service is a generated GoMock package.
package mock_service

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockUnfolowRunner is a mock of UnfolowRunner interface.
type MockUnfolowRunner struct {
	ctrl     *gomock.Controller
	recorder *MockUnfolowRunnerMockRecorder
}

// MockUnfolowRunnerMockRecorder is the mock recorder for MockUnfolowRunner.
type MockUnfolowRunnerMockRecorder struct {
	mock *MockUnfolowRunner
}

// NewMockUnfolowRunner creates a new mock instance.
func NewMockUnfolowRunner(ctrl *gomock.Controller) *MockUnfolowRunner {
	mock := &MockUnfolowRunner{ctrl: ctrl}
	mock.recorder = &MockUnfolowRunnerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUnfolowRunner) EXPECT() *MockUnfolowRunnerMockRecorder {
	return m.recorder
}

// Run mocks base method.
func (m *MockUnfolowRunner) Run(to, from uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", to, from)
	ret0, _ := ret[0].(error)
	return ret0
}

// Run indicates an expected call of Run.
func (mr *MockUnfolowRunnerMockRecorder) Run(to, from interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockUnfolowRunner)(nil).Run), to, from)
}
