// Package server provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.2 DO NOT EDIT.
package server

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/2SSMW8bMQyF/wrBdjz7LsmmzU3RwOiQAm2nIIOqo30CdKIqUrEPgf97ITlIGkcT8SRQ",
	"j9/jMzqeE0eKKmieUdxEs23lbSar9Fsob6NS1KqlzImyemovilCOdqZa65IIDYpmH/d4qqdDH3dcL0cS",
	"l31SzxEN/pq8gBewEeho5xQIeAdFfNzD/abodA0b50gEbnkk+Bb4AD6CBUnk/M47WxuBMpz7/iEQciV7",
	"Xaq4cMmw+bFdY4fqNVRbdww/2Xkb4C7bNNVr7PCJspwtXa2H9YCnDjlRtMmjwZsmdZisTm3a3ibf15Eb",
	"CJYGpOJodrYjmv+QYYeZ/hYS/cLjUl86fqVoUwovU/TH1eFwWO04z6uSA0XHI41vSdTqc6YdGvzUv0XV",
	"v+TUfwipca9f+1z7aC7UBEkc5Rzb9TBcGFI6aj/pHN5//CHT7iLJ++9YRSnzbPPyCgAsRDpAOXNQuxc0",
	"D21b8LF1EcqVPZqHy914l9JXeqLAaa4uOyw5oMFJNZm+D+xsmFjU3AxXQ4+nx9O/AAAA//+C26XjywIA",
	"AA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
